development:
  adapter: postgresql
  database: qscar_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: qscar_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: qscar_production
  pool: 5
  timeout: 5000